import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 https://docusaurus.io/docs/sidebar
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //sidebar: [{ type: "autogenerated", dirName: "." }],
    // Custom sidebar navigation
    docs: [
        'intro',
        {
            type: 'category',
            label: 'Installation',
            link: {
                type: 'doc',
                id: 'installation/index',
            },
            items: [
                {
                    type: 'doc',
                    id: 'installation/bundler',
                    label: 'Bundler (ESM)',
                },
                {
                    type: 'doc',
                    id: 'installation/browser',
                    label: 'Standalone browser script',
                },
                {
                    type: 'doc',
                    id: 'installation/commonjs',
                    label: 'CommonJS',
                },
            ],
        },
        {
            type: 'category',
            label: 'Guides',
            link: {
                type: 'generated-index',
            },
            items: [
                {
                    type: 'doc',
                    id: 'guides/load',
                    label: 'Load the Google Maps library',
                },
                {
                    type: 'category',
                    label: 'Data layer',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'doc',
                            id: 'guides/data-layer/polygons',
                            label: 'Polygons with holes',
                        },
                        {
                            type: 'doc',
                            id: 'guides/data-layer/popups',
                            label: 'Popups on features',
                        },
                        {
                            type: 'doc',
                            id: 'guides/data-layer/shared-map-layer',
                            label: "The map's data layer is shared",
                        },
                        {
                            type: 'doc',
                            id: 'guides/data-layer/tooltips',
                            label: 'Tooltips on features',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Maps',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'doc',
                            id: 'guides/map/display',
                            label: 'Display the map',
                        },
                        {
                            type: 'doc',
                            id: 'guides/map/controls',
                            label: 'Map Controls',
                        },
                        {
                            type: 'doc',
                            id: 'guides/map/styles',
                            label: 'Style the map',
                        },
                        {
                            type: 'doc',
                            id: 'guides/map/display-multiple-maps',
                            label: 'Multiple maps on one page',
                        },
                        {
                            type: 'doc',
                            id: 'guides/map/map-not-visible',
                            label: 'When the map is hidden initially',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Polylines',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'doc',
                            id: 'guides/polyline/highlight',
                            label: 'Highlight a polyline',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Popups',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'doc',
                            id: 'guides/popup/closing',
                            label: 'Closing the popup',
                        },
                        {
                            type: 'doc',
                            id: 'guides/popup/setting-content',
                            label: 'Setting the popup content',
                        },
                        {
                            type: 'doc',
                            id: 'guides/popup/styling',
                            label: 'Styling a polyline',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Tooltips',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'doc',
                            id: 'guides/tooltip/styling',
                            label: 'Styling a tooltip',
                        },
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Plugins',
            link: {
                type: 'doc',
                id: 'plugins',
            },
            items: [
                {
                    type: 'doc',
                    id: 'plugin',
                    label: 'Writing a plugin',
                },
            ],
        },
        {
            type: 'category',
            label: 'API reference',
            link: {
                type: 'generated-index',
                description: 'Learn about the different objects available in the library.',
            },
            items: [
                'api-reference/autocomplete-search-box',
                {
                    type: 'category',
                    label: 'Base classes',
                    link: {
                        type: 'doc',
                        id: 'api-reference/base-classes/index',
                    },
                    items: [
                        'api-reference/base-classes/base',
                        'api-reference/base-classes/evented',
                        'api-reference/base-classes/layer',
                    ],
                },
                'api-reference/constants',
                'api-reference/data-feature',
                'api-reference/data-layer',
                {
                    type: 'category',
                    label: 'Geocoding',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        'api-reference/geocoding/address-component',
                        'api-reference/geocoding/address-types',
                        'api-reference/geocoding/geocode',
                        'api-reference/geocoding/result',
                        'api-reference/geocoding/results',
                    ],
                },
                'api-reference/image-overlay',
                'api-reference/infowindow',
                'api-reference/loader',
                'api-reference/map',
                {
                    type: 'category',
                    label: 'Map Configuration Objects',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        'api-reference/map-configuration/map-restriction',
                        'api-reference/map-configuration/map-style',
                    ],
                },
                {
                    type: 'category',
                    label: 'Map Controls',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        'api-reference/map-controls/button',
                        'api-reference/map-controls/control',
                        'api-reference/map-controls/fullscreen-control',
                        'api-reference/map-controls/location-control',
                        'api-reference/map-controls/map-type-control',
                        'api-reference/map-controls/rotate-control',
                        'api-reference/map-controls/scale-control',
                        'api-reference/map-controls/street-view-control',
                        'api-reference/map-controls/zoom-control',
                    ],
                },
                'api-reference/marker',
                'api-reference/marker-cluster',
                'api-reference/marker-collection',
                'api-reference/overlay',
                'api-reference/places-search-box',
                'api-reference/polyline',
                'api-reference/polyline-collection',
                'api-reference/polyline-icon',
                'api-reference/popup',
                'api-reference/tooltip',
                {
                    type: 'category',
                    label: 'Utilities',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        'api-reference/utilities/icon',
                        'api-reference/utilities/latlng',
                        'api-reference/utilities/latlng-bounds',
                        'api-reference/utilities/point',
                        'api-reference/utilities/size',
                        'api-reference/utilities/svgsymbol',
                    ],
                },
            ],
        },
    ],
};

export default sidebars;
